### ISSUE TITLE
IP2LOCATION-LITE-DB1.IPV6.BIN manually download and use not working ?

### ISSUE THREAD

**Issue by Tob1as** [nscuro/traefik-plugin-geoblock#76]
Hello,

I have a question because I don't understand something. 

Basically the plugin works fine. My config:
In **Traefik 2.x** docker-compose as command:
```yaml
- "--experimental.plugins.geoblock.modulename=github.com/nscuro/traefik-plugin-geoblock"
- "--experimental.plugins.geoblock.version=v0.11.0"
```
Volume `- ./traefik-plugins/:/plugins-local/`
Traefik dynamic config:
```yaml
http:
  middlewares:
    geoblock:
      plugin:
        geoblock:
          # Enable this plugin?
          enabled: true
          # Path to ip2location database file
          #databaseFilePath: /plugins-storage/sources/gop-<random-numbers>/src/github.com/nscuro/traefik-plugin-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN
          databaseFilePath: /plugins-local/IP2LOCATION-LITE-DB1.IPV6.BIN
          # Whitelist of countries to allow (ISO 3166-1 alpha-2)
          allowedCountries: [ "DE" ]
          # Allow requests from private / internal networks?
          allowPrivate: true
          # HTTP status code to return for disallowed requests (default: 403)
          disallowedStatusCode: 403
          # Add CIDR to be whitelisted, even if in a non-allowed country
          allowedIPBlocks: ["x.x.x.x/32"]
```
For Service (test with whoami) i add in compose file:
`- "traefik.http.routers.whoami.middlewares=geoblock@file"`

First i use `/plugins-storage/sources/gop-<random-numbers>/src/github.com/nscuro/traefik-plugin-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN` as databaseFilePath. But with every Traefik restart the numbers in the path change, so I copied the file to /plugins-local/ and changed the databaseFilePath to this path.  
(Path /plugins-local/src/github.com/nscuro/traefik-plugin-geoblock/ from project Readme default not exists.)  
This also works, not allowed countries are blocked!

But now I want to use the latest version of IP2LOCATION-LITE-DB1.IPV6.BIN and have downloaded it from the website https://lite.ip2location.com/database/ip-country and overwrite the old file. (The permissions are the same: chmod 755 and root user.)(The bin file is a bit larger.)
But this not working, it does not work even after restarting Traefik and the service. No errors are displayed in Traefik Dashboard.
I have access from allowed country and all others.

What could be the reason for this? Can I somehow see the logs from Geoblock to see if there is an error when reading the file? (My Traefik log-level is debug.)
